package com.mscode.playercard.remote.response

import kotlinx.serialization.Serializable

@Serializable
class TeamResponse (
    val idTeam: String,
    val idESPN: String?,
    val idAPIfootball: String?,
    val intLoved: String?,
    val strTeam: String,
    val strTeamAlternate: String?,
    val strTeamShort: String?,
    val intFormedYear: String?,
    val strSport: String?,
    val strLeague: String?,
    val idLeague: String?,
    val strLeague2: String?,
    val idLeague2: String?,
    val strLeague3: String?,
    val idLeague3: String?,
    val strLeague4: String,
    val idLeague4: String?,
    val strLeague5: String?,
    val idLeague5: String?,
    val strLeague6: String?,
    val idLeague6: String?,
    val strLeague7: String?,
    val idLeague7: String?,
    val strDivision: String?,
    val idVenue: String?,
    val strStadium: String?,
    val strKeywords: String?,
    val strRSS: String?,
    val strLocation: String?,
    val intStadiumCapacity: String?,
    val strWebsite: String?,
    val strFacebook: String?,
    val strTwitter: String?,
    val strInstagram: String?,
    val strDescriptionEN: String?,
    val strDescriptionFR: String?,
    val strColour1: String?,
    val strColour2: String?,
    val strColour3: String?,
    val strGender: String?,
    val strCountry: String?,
    val strBadge: String?,
    val strLogo: String?,
    val strFanart1: String?,
    val strFanart2: String?,
    val strFanart3: String?,
    val strFanart4: String?,
    val strBanner: String?,
    val strEquipment: String?,
    val strYoutube: String?,
    val strLocked: String?,
)