package com.mscode.playercard.domain.fake

import com.mscode.playercard.domain.models.Player
import com.mscode.playercard.domain.models.Team

object TestDomainFactory {
    fun createPlayer(
        idPlayer: String = "1",
        idTeam: String = "133604",
        strPlayer: String = "Lionel Messi",
        strNationality: String = "Argentina",
        strPosition: String = "Forward"
    ) = Player(
        idPlayer = idPlayer,
        idTeam = idTeam,
        idTeam2 = null,
        idTeamNational = null,
        idAPIfootball = null,
        idPlayerManager = null,
        idWikidata = null,
        idTransferMkt = null,
        idESPN = null,
        strNationality = strNationality,
        strPlayer = strPlayer,
        strPlayerAlternate = null,
        strTeam = "PSG",
        strTeam2 = null,
        strSport = "Soccer",
        intSoccerXMLTeamID = null,
        dateBorn = "1987-06-24",
        dateDied = null,
        strNumber = "30",
        dateSigned = "2021-08-10",
        strSigning = "Free",
        strWage = "35000000",
        strOutfitter = "Adidas",
        strKit = null,
        strAgent = null,
        strBirthLocation = "Rosario, Argentina",
        strEthnicity = null,
        strStatus = "Active",
        strDescriptionEN = "One of the greatest players",
        strDescriptionDE = null,
        strDescriptionFR = null,
        strDescriptionCN = null,
        strDescriptionIT = null,
        strDescriptionJP = null,
        strDescriptionRU = null,
        strDescriptionES = null,
        strDescriptionPT = null,
        strDescriptionSE = null,
        strDescriptionNL = null,
        strDescriptionHU = null,
        strDescriptionNO = null,
        strDescriptionIL = null,
        strDescriptionPL = null,
        strGender = "Male",
        strSide = "Left",
        strPosition = strPosition,
        strCollege = null,
        strFacebook = null,
        strWebsite = null,
        strTwitter = null,
        strInstagram = null,
        strYoutube = null,
        strHeight = "170 cm",
        strWeight = "72 kg",
        intLoved = "999999",
        strThumb = "https://example.com/thumb.jpg",
        strPoster = null,
        strCutout = "https://example.com/cutout.png",
        strRender = null,
        strBanner = null,
        strFanart1 = null,
        strFanart2 = null,
        strFanart3 = null,
        strFanart4 = null,
        strCreativeCommons = "Yes",
        strLocked = "unlocked"
    )

    fun createTeam(
        teamId: String = "133604",
        strTeam: String = "Paris Saint-Germain",
        strLeague: String = "French Ligue 1",
        strStadium: String = "Parc des Princes",
        strCountry: String = "France"
    ) = Team(
        teamId = teamId,
        strTeam = strTeam,
        intFormedYear = "1970",
        strLeague = strLeague,
        strDivision = "1",
        strStadium = strStadium,
        strLocation = "Paris",
        intStadiumCapacity = "47929",
        strWebsite = "www.psg.fr",
        strFacebook = "www.facebook.com/PSG",
        strTwitter = "twitter.com/PSG_inside",
        strInstagram = "instagram.com/psg",
        strDescriptionEN = "Paris Saint-Germain Football Club",
        strDescriptionFR = "Paris Saint-Germain Football Club",
        strGender = "Male",
        strCountry = strCountry,
        strBadge = "https://example.com/badge.png",
        strLogo = "https://example.com/logo.png",
        strFanart1 = "https://example.com/fanart.jpg",
        strEquipment = "Nike"
    )
}